-- GOLAZO 利益管理：月別経費
create table if not exists public.profit_expenses (
  id bigint generated by default as identity primary key,
  expense_month text not null,
  category text not null,
  amount numeric not null default 0,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint profit_expenses_month_format
    check (expense_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),

  constraint profit_expenses_amount_nonnegative
    check (amount >= 0),

  constraint profit_expenses_month_category_unique
    unique (expense_month, category)
);

alter table public.profit_expenses enable row level security;

create policy "authenticated_full_access"
on public.profit_expenses
for all
to authenticated
using (true)
with check (true);

create index if not exists profit_expenses_month_idx
on public.profit_expenses (expense_month);
